# Generated by Django 3.1.2 on 2020-10-14 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('list_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=250, null=True)),
                ('poster_path', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'list_movies',
            },
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'lists',
            },
        ),
    ]
