# Generated by Django 3.1.2 on 2020-10-15 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('ref', models.CharField(max_length=50)),
                ('ref_id', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
    ]
